
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aditya
 */
class chatClient implements Runnable{
    Socket SOCK;
    ClientGUI GUI;
    PrintWriter OUT;
    Scanner sc;
    
    chatClient(Socket SOCK, ClientGUI GUI) throws IOException{
        this.SOCK = SOCK;
        this.GUI = GUI;
    }
    @Override
    public void run() {
        try {
            //        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            OUT = new PrintWriter(SOCK.getOutputStream());
            sc = new Scanner(SOCK.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(chatClient.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Cannot set input and output streams");
        }
        OUT.println(GUI.thname.getText());
        OUT.println(GUI.thname.getText());
        OUT.println("Welcome");
        OUT.flush();
        String inp;
        while(true){
            if(sc.hasNext()){
                inp = sc.nextLine();
                System.out.println(inp);
                GUI.chatta.append(inp + "\n");
            }
        }
    }
    public void sendMsg(String msg){
//        String msg = GUI.thname.getText() + "\n" + GUI.Nametf.getText() + " : " + GUI.msgta.getText();
        OUT.println(msg);
        OUT.flush();
    }
    
}
public class ClientGUI extends javax.swing.JFrame {
    chatClient Client;
    boolean isConnected;
    int PORT;
    String HOST;
    Socket SOCK;
//    PrintWriter OUT;
//    Scanner IN;
    String username;
    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
//        sendB.setEnabled(false);
        sendB.setEnabled(false);
        Nametf.setEnabled(false);
        msgta.setEnabled(false);
        chatta.setEditable(false);
    }
    public void Connect() throws IOException{
        SOCK = new Socket (HOST,PORT);
        isConnected = true;
        Client = new chatClient(SOCK,this);
        Thread tClient = new Thread(Client);
        tClient.start();
        String msg = "You are connected to : " + HOST + ":" + PORT;
        System.out.println(msg);
        chatta.append( msg + "\n");
    }
    public boolean checkConnected(){
        if(SOCK.isConnected()){
            return true;
        } else {
            isConnected = false;
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Hosttf = new javax.swing.JTextField();
        Porttf = new javax.swing.JTextField();
        sendB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatta = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        logoutB = new javax.swing.JButton();
        clearB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        thname = new javax.swing.JTextField();
        connectb = new javax.swing.JButton();
        msgta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name :");

        jLabel2.setText("Message:");

        jLabel3.setText("Host:");

        jLabel4.setText("Port:");

        sendB.setText("Send");
        sendB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBActionPerformed(evt);
            }
        });

        chatta.setColumns(20);
        chatta.setRows(5);
        jScrollPane2.setViewportView(chatta);

        jLabel5.setText("Chat History");

        logoutB.setText("Logout");

        clearB.setText("Clear");

        jLabel6.setText("Name:");

        thname.setText("aadi");

        connectb.setText("Connect");
        connectb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Hosttf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Porttf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(thname, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(connectb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearB, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(msgta, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(sendB, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Hosttf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Porttf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutB)
                    .addComponent(clearB)
                    .addComponent(jLabel6)
                    .addComponent(thname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(msgta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBActionPerformed
        if(!checkConnected()){
            chatta.append("Connection Lost!! :(\n");
            sendB.setEnabled(false);
            Nametf.setEnabled(false);
            msgta.setEnabled(false);
        } else {
            String msg = Nametf.getText() + "\n" + msgta.getText();
            Client.sendMsg(msg);
            chatta.append("To " + Nametf.getText() + " : " + msgta.getText() + "\n");
            msgta.setText("");
            msgta.requestFocus();
        }
    }//GEN-LAST:event_sendBActionPerformed

    private void connectbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectbActionPerformed
        if(!isConnected){
            HOST = Hosttf.getText();
            String temp_name = thname.getText();
            if(temp_name == null || temp_name.equals("")){
                chatta.append("Improper username\n");
                System.out.println("Inavalid username");
                return;
            }
            try{
                PORT = Integer.parseInt(Porttf.getText());
                Connect();
                sendB.setEnabled(true);
                Nametf.setEnabled(true);
                msgta.setEnabled(true);
                this.getRootPane().setDefaultButton(sendB);
                Nametf.requestFocus();
            } catch (NumberFormatException e){
                System.out.println("Invalid port no.");
                chatta.append("Improper port " + Porttf.getText() + "\n");
                Porttf.requestFocus();
                return;
            } catch (IOException ex) {
                System.out.println(ex);
                chatta.append("Not found " +HOST + ":" + PORT + "\n");
                return;
            }
        }
    }//GEN-LAST:event_connectbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Hosttf;
    public javax.swing.JTextField Nametf;
    public javax.swing.JTextField Porttf;
    public javax.swing.JTextArea chatta;
    public javax.swing.JButton clearB;
    public javax.swing.JButton connectb;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton logoutB;
    public javax.swing.JTextField msgta;
    public javax.swing.JButton sendB;
    public javax.swing.JTextField thname;
    // End of variables declaration//GEN-END:variables
}
